### ISSUE TITLE
Sorry for this but couldn't find a way to get a hold of you otherwise

### ISSUE THREAD

**Issue by Masamune3210** [sTiKyt/OrangeConfigs#2]
Just use this. Don't give those Androcity fscks the time of day or the attention and money they so desperately crave. 
https://github.com/ya0211/MRepo

**Comment by sTiKyt** [comment]
Thanks a lot, I appreciate that 👍

Was hoping there was something sane, not messed up by them

**Comment by Masamune3210** [comment]
They are absolutely atrocious and have no qualms with what they are knowingly doing. Steer away from anything even slightly involving them and you will have a better time, trust me.
